name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Building Application"
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: echo "Running TestCases"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: production # Ask for Approval
    steps:
      - name: Deploy
        run: echo "Deploying app to production"